apiVersion: v1
kind: Template
labels:
  app: freelance4j-project-service
metadata:
  annotations:
    description: project service persistent template for MongoDB
  name: freelance4j-project-mongodb
objects:
# Project Service
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: project-service
    name: project-mongodb
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      deploymentconfig: project-mongodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: project-service
    name: project-mongodb
  spec:
    replicas: 1
    selector:
      deploymentconfig: project-mongodb
    strategy:
      recreateParams:
        post:
          execNewPod:
            command:
              - /bin/sh
              - -i
              - -c
              - sleep 10 && /opt/rh/rh-mongodb32/root/usr/bin/mongo $PROJECT_MONGODB_SERVICE_HOST:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="$MONGODB_INIT"
            containerName: project-mongodb
            env:
            - name: MONGODB_INIT
              value: db.projects.insert({"_id":"329299","projectId":"329299","ownerFirstName":"Ricardo","ownerLastName":"Feijao","ownerEmailAddress":"ricardidot@gmail.com",
               "projectTitle":"Tratativa de erro no projeto","projectDescription":"Tratativa de erro no projeto","projectStatus":"open"});
               db.projects.insert({"_id":"1215","projectId":"1215","ownerFirstName":"Julio","ownerLastName":"Colin","ownerEmailAddress":"jula@gmail.com",
               "projectTitle":"Conversao de codigos","projectDescription":"Conversao de codigos","projectStatus":"in_progress"});
               db.projects.insert({"_id":"1216","projectId":"1216","ownerFirstName":"Marta","ownerLastName":"Julo","ownerEmailAddress":"monkey1@gmail.com",
               "projectTitle":"Projeto petshop","projectDescription":"Projeto petshop","projectStatus":"completed"});
               db.projects.insert({"_id":"1217","projectId":"1217","ownerFirstName":"Cristina","ownerLastName":"Miyd","ownerEmailAddress":"teresa@gmail.com",
               "projectTitle":"Compra e vendas de tenis","projectDescription":"Compra e vendas de tenis","projectStatus":"cancelled"});                                
          failurePolicy: ignore
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: project-service
          deploymentconfig: project-mongodb
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MONGODB_USER
            value: ${PROJECT_DB_USERNAME}
          - name: MONGODB_PASSWORD
            value: ${PROJECT_DB_PASSWORD}
          - name: MONGODB_DATABASE
            value: ${PROJECT_DATABASE}
          - name: MONGODB_ADMIN_PASSWORD
            value: ${PROJECT_DB_PASSWORD}
          image: mongodb
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: project-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data-pv
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - project-mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      application: project-mongodb
    name: mongodb-data-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
- description: Project Service database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: PROJECT_DB_USERNAME
  required: true
- description: Project Service database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: PROJECT_DB_PASSWORD
  required: true
- description: Project Service database name
  name: PROJECT_DATABASE
  required: true
  value: projectdb
